### ISSUE TITLE
requirement incompatibility

### ISSUE THREAD

**Issue by mautronic** [blockchain-certificates/cert-issuer#174]
I have installed the next packages to setup a blockcerts system: cert-tools, cert-core, cert-issuer, cert-verifier, cert-viewer

I found a compatibility error of some requirements:
ERROR: merkletools 1.0.2 has requirement pysha3==1.0b1, but you'll have pysha3 1.0.2 which is incompatible.
ERROR: flasgger 0.9.4 has requirement jsonschema>=3.0.1, but you'll have jsonschema 2.6.0 which is incompatible.
ERROR: cert-viewer 2.0.1 has requirement configargparse>=0.13.0, but you'll have configargparse 0.12.0 which is incompatible.
ERROR: cert-tools 2.0.11 has requirement configargparse>=0.13.0, but you'll have configargparse 0.12.0 which is incompatible.

Will you push any update on the requirements or is there any fix I can do?
Thank you!

**Comment by AnthonyRonning** [comment]
This ticket provides a bit more context to the issue: https://github.com/blockchain-certificates/cert-issuer/issues/102

It's been a problem for us navigating these dependencies and libraries that won't update to fix the issue. For now, yeah you can manually edit the dependency version `site-package` for it once installed. Check out the link for more info.

**Comment by mautronic** [comment]
> This ticket provides a bit more context to the issue: #102
> 
> It's been a problem for us navigating these dependencies and libraries that won't update to fix the issue. For now, yeah you can manually edit the dependency version `site-package` for it once installed. Check out the link for more info.

This worked just fine!!
I modified the METADATA file at ~Lib\site-packages\cert_tools-2.0.11.dist-info
and the respective dist-info folders for each error I had. I just changed the <package_name> == <version> 
to
<package_name> >= <lower_version_of the error message>

Thank you!

**Comment by JuanVentrone** [comment]
I can´t build a image, conflict dependencies can any one help me


INFO: pip is looking at multiple versions of cert-core to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pycoin to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of mock to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of glob2 to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of configargparse to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of cert-issuer to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install cert-issuer==2.0.27 and chainpoint because these package versions have conflicting dependencies.

The conflict is caused by:
    cert-issuer 2.0.27 depends on pysha3>=1.0.2
    merkletools 1.0.2 depends on pysha3==1.0b1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

**Comment by JuanVentrone** [comment]
I can´t build a image, conflict dependencies can any one help me


INFO: pip is looking at multiple versions of cert-core to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pycoin to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of mock to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of glob2 to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of configargparse to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of cert-issuer to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install cert-issuer==2.0.27 and chainpoint because these package versions have conflicting dependencies.

The conflict is caused by:
    cert-issuer 2.0.27 depends on pysha3>=1.0.2
    merkletools 1.0.2 depends on pysha3==1.0b1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
