### ISSUE TITLE
Doc: About docker-machine

### ISSUE THREAD

**Issue by nc163** [blockchain-certificates/cert-issuer#250]
The README.md says docker-machine is required. -> https://github.com/blockchain-certificates/cert-issuer/blob/master/docs/docker_install.md

I looked it up and found an article about it being discontinued.

https://matsuand.github.io/docs.docker.jp.onthefly/machine/

Is docker-machine still required?

**Comment by lemoustachiste** [comment]
I honestly don't use this package with docker so I don't know.
There hasn't been much work on the Docker aspect of this package (mainly because of the above reason), so it's likely it has not kept up with the tech.

So 2 things:
- as is, I suppose you need docker-machine (although you could try without)
- if you find a way to remove the dependency to a deprecated package and things work, by all means please open a PR :)

Thanks
