### ISSUE TITLE
Not Able to generate certificate using cert-issuer

### ISSUE THREAD

**Issue by aayushgarg01** [blockchain-certificates/cert-issuer#76]
Hi,

I am sorry if it comes out as a silly (very basic) question but while using cert-issuer instructions here https://github.com/blockchain-certificates/cert-issuer
in the "Creating issuing address" there is a statement to be executed under bitcoin bash: 

**sed -i.bak "s/**issuing-address**/$issuer/g" /etc/cert-issuer/conf.ini**

in this what is the difference between **issuing-address** and **$issuer** ?
I believe $issuer is what I generated just above this statement ( issuer=`bitcoin-cli getnewaddress` ), but the what is **issuing-address** ?

Later when I am trying to execute "bitcoin-cli sendtoaddress $issuer 5"
This isn't working either, and due to this I am not able to generate certificate as it is saying insufficient balance.

Can you please help me with this.

Regards
Aayush

**Comment by kimdhamilton** [comment]
Hi Aayush,
That is simply a find-and-replace. It's replacing the fixed string value in the config file with the issuer address created on the command line. `issuing-address` is just a constant placeholder value from conf-template.ini, which is the source of conf.ini.

If something isn't working, I recommend re-running the steps. You could try copying and pasting the steps from this script instead of using the README. https://github.com/blockchain-certificates/cert-issuer/blob/master/regtest_script.sh
Thanks,
Kim

**Comment by kimdhamilton** [comment]
Please re-open if that didn't address your concern.
